### PR TITLE
Fix start with delta parameter

### LINKED ISSUE #218: Start and delta cannot be used together
How to reproduce:
https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.copr.build.end&start=1552536775&delta=36000

Actual results:
```
{"detail":"unsupported operand type(s) for -: 'float' and 'unicode'","error":"internal_error","traceback":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/lib/python2.7/site-packages/datagrepper/app.py\", line 271, in raw\n    start, end, delta = assemble_timerange(start, end, delta)\n  File \"/usr/lib/python2.7/site-packages/datagrepper/util.py\", line 68, in assemble_timerange\n    delta = end - start\nTypeError: unsupported operand type(s) for -: 'float' and 'unicode'\n"}
```

Expected data:
No exceptions and real data are returned.

BTW documentation says it should be supported:
https://apps.fedoraproject.org/datagrepper/reference#time-arguments

### PR DESCRIPTION
**Pull request by hluk**
Fixes #218

Signed-off-by: Lukas Holecek <hluk@email.cz>

### CODE REVIEW

**Comment by hluk** [comment]
#223 fixes for the py27 tox env.

**Comment by mikebonnet** [comment]
+1 Looks good.

**Comment by pypingou** [comment]
Could you rebase so we can see what travis says now?

**Comment by hluk** [comment]
> Could you rebase so we can see what travis says now?

Rebased.

**Comment by pypingou** [comment]
Travis is happy, let's get this in :)

**Pull request merged**
